### ISSUE TITLE
Apparent broken links in README.md

### ISSUE THREAD

**Issue by pbrubaker** [ssteinberg/PLTFalcor#2]
Hey there.  The hyperlinks at the end of these two sentences appear to be broken.

> Additional rendered images and videos available [here]().

> A few sample scenes with diffractive materials can be found [here]().

They redirect to https://github.com/ssteinberg/PLTFalcor/blob/master but that's a blank page.

**Comment by pbrubaker** [comment]
Hey thanks for the quick response @ssteinberg!  This link still appears to be broken though.

> Additional rendered images and videos available [here]().

**Comment by ssteinberg** [comment]
Ah yes, that too. Fixed.

**Comment by pbrubaker** [comment]
Thanks!
